---
title: "Home Energy Management – Starting Line"
date: "2022-10-05"
description: >
  Our original way of using energy resources.
categories:
  - energy
---

My main motivation for starting this blog site in the first place was to document the transition of our household from traditional energy consumption patterns to a more clever energy management.

I've had several motivations to do so:

* create kind of project documentation that might come handy later
* writing about a technical solution may help identify weak or overly complex points of the solution itself – if I am not able to describe it in a comprehensible manner, then it has to be redone or at least refactored
* other people facing similar challenges may learn from our experience and avoid repeating our mistakes, and also provide feedback.

Indeed, our home is kind of traditional two-storey family house (at least according to Czech standards) built in 2004, located near [České Budějovice](https://en.wikipedia.org/wiki/%C4%8Cesk%C3%A9_Bud%C4%9Bjovice) in the altitude of 406 m above the sea level. We live in it together with my wife.

We currently use natural gas for heating and preparing hot water, for cooking and everything else we use electricity. In each of our two bathrooms we have a towel radiator that is connected to a central heating system, but also has a separate electric heating element that can be switched on independently.

In 2019, our 15 years old gas-fired boiler broke down and had to be promptly replaced. At that time, with no energy crisis yet in sight, it looked like a no-brainer to buy a gas condensing boiler as a replacement, and that's what we did.

# Energy bills

Anyway, our energy consumption in the last five years is shown in @tbl-consumption. The condensing boiler apparently caused about 10% decrease in natural gas use. Electricity consumption rose in 2020 and 2021, which clearly has to do with the covid pandemic, as we both were working mostly from home office.

| Year | Electricity [MWh] | Gas [MWh] |
|------|------------------:|----------:|
| 2017 |             2.497 |    25.857 |
| 2018 |             2.365 |    23.738 |
| 2019 |             2.371 |    23.563 |
| 2020 |             2.636 |    20.838 |
| 2021 |             2.914 |    22.996 |

: Yearly energy consumption 2017–2021 {#tbl-consumption}

In any case, with our current electricity consumption the investment in a photovoltaic power plant (that was going to happen in late 2022, see TODO) would take quite long to return, even with current high energy prices. Unless, of course, we change the ways how we use electricity.

# Immediate actions

We have made a few significant steps already in 2022, i.e. before the PV system was installed. This section contains only a brief overview, some of these steps certainly deserve a closer look in future blog posts.

First of all, I bought a couple of smart plugs capable of measuring instantaneous power and energy output, with two aims:

* evaluate actual power consumption of home appliances

* enable remote control of selected appliances, especially heaters, with the prospect of including them in automation scenarios.

Regarding automation, I must admit that I am not a big fan of so-called smart homes. I think we can still operate lights and make our cups of tea manually. On the other hand, with electricity flowing down from our roof it makes a lot of sense to plan a bit ahead and turn on appliances, in particular the greedy ones, at appropriate times in order to minimize consumption from the grid. This is where a limited amount of automation comes handy.

In June

# What next?
