project:
  type: website

website:
  title: "Blog Matrix"
  favicon: logo.svg
  site-url: https://llhotka.github.io
  description: "This is Ladislav Lhotka's personal blog."
  navbar:
    background: "#A7D5E8"
    logo: "logo.svg"
    collapse-below: lg

    right:
      - about.qmd
      - archive.qmd
      - icon: github
        href: https://github.com/llhotka
      - icon: twitter
        href: https://twitter.com/LadislavLhotka
format:
  html:
    theme: cosmo
    css: styles.css

