project:
  type: website

website:
  title: "Ladislav Lhotka"
  site-url: https://llhotka.github.io
  description: "This is Ladislav Lhotka's personal blog."
  navbar:
    right:
      - about.qmd
      - archive.qmd
      - icon: github
        href: https://github.com/llhotka
      - icon: twitter
        href: https://twitter.com/LadislavLhotka
format:
  html:
    theme: cosmo
    css: styles.css


